### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by gfddfgdgfdh** [caspianite/simplemmo-web#1]
Hey, i will train a AI to solve those captchas, will you help me retrieving the images of the captchas / wanted answer?

**Comment by gfddfgdgfdh** [comment]
Also attack entities is outdated

**Comment by caspianite** [comment]
> Hey, i will train a AI to solve those captchas, will you help me retrieving the images of the captchas / wanted answer?

hello sorry for not replying but this repository is basically dead and for learning purposes

there is no need to use image recognition, it's enough to just bruteforce random choices until it gets the right answer on the challenge (one image is right out of 4, 25% chance and no rate limiting, the minimum time i got with no artificial slow downs was 2-9s per captcha solve)
